apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: mygke-756
  git:
    syncRepo: https://github.com/mathieu-benoit/my-kubernetes-deployments
    syncBranch: main
    secretType: none
    policyDir: .